### ISSUE TITLE
Replaced words appear wrong location

### ISSUE THREAD

**Issue by Computeroid** [outpoot/bliptext#17]
Words meant to replace URLS showing up further down the page.

This may be happening because it is indexing the file's words wrong or because of issues with concurrent updates to the file.

#### Example:

[https://bliptext.com/articles/twitter/](https://bliptext.com/articles/twitter/edit)
I replaced 'tweets' with 'a-very-long-word-lmao-1-2-3-4-5-6-7-8-9-10-11-12-1' and it seemed to think that I was referencing position 600 after failing to update the first time. The original replacement was possibly out of sync and the second attempt looked for the next occurrence or something.

**Comment by face-hh** [comment]
Has this happened recently? Because we've just recently decreased the debounce between /hover updates, which previously caused a context mismatch.

**Comment by face-hh** [comment]
Alright, I'll assume it has been fixed.

If it happens again, feel free to comment on this issue & I'll get notified.

Will be closing for now to keep track of on-going confirmed issues

**Comment by sierra-madre** [comment]
It actually isn't fixed. I can't provide screenshots at the moment (since the site appears to be down), but I'll retell how it was for me.
I was editing the article on Azumanga Daioh, and somewhere near the start was the word "manga" with a hyperlink.
When I tried to replace it first time, it appeared to be replaced, but refreshing the page showed me that it wasn't replaced.
In the edit history, it shows that it updated the same word "manga", but on the different position (i assume, the next position of this word in the whole article). Let's call this second word B, and the first A.
I scrolled down, and, well, as the history told me, it changed the next position of same word, it was Manga B now.
I tried replacing the very first Manga A again, but it replaced the next position of the word again. Note that it replaced the next word, not the Manga B. The next word after Manga B was replaced.
I was doing this for a while until every "manga" was replaced in the next except the Manga A, the very first one. I tried replacing it, and it finally worked.
Basically it was replacing every instance of that word except the one I wanted to replace, until no other instances were available, and it finally accepted it's fate and let me replace it.
Two notes:
1. It is case-sensitive and accurate. Only "manga" were treated as other instances that it replaced instead of the very first one. "Manga" or "manga-something"
2. Other instances don't have to be hyperlinks, they're normal words. I'm not sure if other hyperlinks with the same word aren't treated as valid instances for this, though. Again, the site is down and I can't check.
