### ISSUE TITLE
No support for unicode characters other than the alphanumeric ones.

### ISSUE THREAD

**Issue by bragosmagos** [outpoot/bliptext#4]
When editing a word, we can only use letters, digits and "_". We are unable to use commas, semicolons, dots and other characters needed for proper grammar. In addition, this also makes us unable to use a proper paragraph sign, and many others. Ideally, the entirety of the unicode standard should be supported.

If single-character spamming becomes an issue, such as replacing words with only "......." or "aaaaaaa", this could easily be prevented by not allowing more than a set number of the same consecutive characters.

**Comment by Sakura-sx** [comment]
https://github.com/outpoot/bliptext/commit/eea6f773b738999c0bc104407c1d7d7a6e9e10ac

Should be fixed on this commit.

**Comment by face-hh** [comment]
Fixed in latest commit

**Comment by face-hh** [comment]
Reopen if it persists

**Comment by bragosmagos** [comment]
The issue persists. When attempting to replace words with "adipiscing," and "elit," in the YouTube article, the words were replaced, but without the commas. For instance, I inputted "adipiscing,", the mouse hover thingy displayed "adipiscing,", yet when the word was replaced the word in the article just read "adipiscing" without the comma.

**Comment by bragosmagos** [comment]
Also, I do not have permissions to reopen.

**Comment by face-hh** [comment]
For clarification: the word validation algorithm has been updated again, presumably fixing this issue.
